"""add_turn_id_to_chat_messages

Revision ID: cb29c2e523f4
Revises: acb98b566401
Create Date: 2025-11-27 01:40:59.483111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb29c2e523f4'
down_revision: Union[str, None] = 'acb98b566401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. nullable=True로 먼저 컬럼 추가
    op.add_column('chat_messages', sa.Column('turn_id', sa.Integer(), nullable=True))

    # 2. 기존 데이터에 기본값 설정 (id 기준으로 순차적 turn_id 부여)
    op.execute("""
        UPDATE chat_messages
        SET turn_id = sub.row_num
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY chat_room_id ORDER BY created_at) as row_num
            FROM chat_messages
        ) sub
        WHERE chat_messages.id = sub.id
    """)

    # 3. NOT NULL 제약조건 추가
    op.alter_column('chat_messages', 'turn_id', nullable=False)

    op.create_index(op.f('ix_chat_messages_turn_id'), 'chat_messages', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_turn_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'turn_id')
    # ### end Alembic commands ###
